#
# template for the pipeline buildspec.yml
#

version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -t uvalib/virgo4-pool-solr-ws:latest .
      - docker tag uvalib/virgo4-pool-solr-ws:latest 115119339709.dkr.ecr.us-east-1.amazonaws.com/uvalib/virgo4-pool-solr-ws:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest image to ECR...
      - docker push 115119339709.dkr.ecr.us-east-1.amazonaws.com/uvalib/virgo4-pool-solr-ws:latest

#
# end of file
#
