#
# buildspec.yml
#

version: 0.2

env:
  variables:
    tag: $(date +%Y%m%d%H%M%S)

phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -f pipeline/Dockerfile -t ${CONTAINER_IMAGE}:latest .
      - docker tag ${CONTAINER_IMAGE}:latest ${CONTAINER_REGISTRY}/${CONTAINER_IMAGE}:latest
      - docker tag ${CONTAINER_IMAGE}:latest ${CONTAINER_REGISTRY/${CONTAINER_IMAGE}/build-${tag}
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest image to ECR...
      - docker push ${CONTAINER_REGISTRY}/${CONTAINER_IMAGE}:latest
      - docker push ${CONTAINER_REGISTRY}/${CONTAINER_IMAGE}:build-${tag}

#
# end of file
#
